const dbConnect = require("../config/dbConnect");
const seeder = require("../config/dbSeed");
const Songs = require("../models/songModel");
const { v4 } = require("uuid");

dbConnect;

const songs = [
  new Songs({
    id: v4(),
    title: "My Love",
    artists: ["644a88b5849a447b4d2c56da"],
    lyrics: "Here we are now, entertain us",
    about: "This is a song about the birds and the bees and the mutha fuckin trees",
    releaseDate: new Date(),
    producedBy: ["Kid skip"],
    writtenBy: ["Danny boy", "Bird Brain"],
    arranger: ["Mr. Los"],
    composer: ["Hunny Dew"],
    lyricist: ["Kid Skip"],
    covers: ["Mi Amor"],
    genres: ["Hard Rock", "Pop", "Goth", "Industrial"],
  }),
  new Songs({
    id: v4(),
    title: "In Utero",
    artists: ["644a88b5849a447b4d2c56da"],
    lyrics: "I wish I could eat your cancer when you turn black",
    about: "The best lyrics on the planet my G",
    releaseDate: new Date(),
    producedBy: ["Kid skip"],
    writtenBy: ["bunny hop", "masta P"],
    arranger: ["cunning lingus"],
    composer: ["Hunny Dew"],
    lyricist: ["Kid Skip", "mad flava"],
    covers: ["Uterus", "placebo"],
    genres: ["Hard Rock", "Goth", "Industrial"],
  }),
  new Songs({
    id: v4(),
    title: "Blackhole Sun",
    artists: ["644a88b5849a447b4d2c56da"],
    lyrics: "Won't you come, and wash away the pain, blackhole sun",
    about: "A song about a sun that has a black hole",
    releaseDate: new Date(),
    producedBy: ["Rocketman"],
    writtenBy: ["bunny hop", "skipitty do"],
    arranger: ["some young gai"],
    composer: ["mountain Dew"],
    lyricist: ["Kid man", "man kid"],
    covers: ["galaxy", "we are made of stars"],
    genres: ["Hard Rock", "grunge", "k-pop"],
  }),
  new Songs({
    id: v4(),
    title: "Love like this",
    artists: ["644a88b5849a447b4d2c56da"],
    lyrics: "I'm the sexiest person alive, and I love like this",
    about: "spoken like a true narcissist",
    releaseDate: new Date(),
    producedBy: ["kid rick", "spondoolie"],
    writtenBy: ["rusty"],
    arranger: ["Boris"],
    composer: ["Yeltsin"],
    lyricist: ["mango", "the russian"],
    covers: ["bilhorod"],
    genres: ["grunge", "k-pop"],
  }),
  new Songs({
    id: v4(),
    title: "I hate everything about you",
    artists: ["644a88b5849a447b4d2c56da"],
    lyrics: "the #1 chart topper amongst ppl who hate things",
    about: "angry singer yells at sky",
    releaseDate: new Date(),
    producedBy: ["pickle rick", "sponge bob"],
    writtenBy: ["rusty"],
    arranger: ["Ivan richtman"],
    composer: ["cudi"],
    lyricist: ["hooga", "booga", "boo"],
    covers: ["coup d'etat"],
    genres: ["hardstyle"],
  }),
  new Songs({
    id: v4(),
    title: "the cracks",
    artists: ["644a88b5849a447b4d2c56da"],
    lyrics: "master of all the things",
    about: "barely made it on the list of music",
    releaseDate: new Date(),
    producedBy: ["nunya"],
    writtenBy: ["nails"],
    arranger: ["dale earnhardt"],
    composer: ["humdinger"],
    lyricist: ["ali baba"],
    covers: ["fed", "local", "state"],
    genres: ["screamo"],
  }),
  new Songs({
    id: v4(),
    title: "Drone watchers",
    artists: ["644a88b5849a447b4d2c56da"],
    lyrics: "look at all those damn drones, all the drones in the skyyyyy",
    about: "made during a time of war",
    releaseDate: new Date(),
    producedBy: ["bunker boi"],
    writtenBy: ["Vlad"],
    composer: ["Klitchsko"],
    lyricist: ["firemaker"],
    covers: ["where there's smoke there's fire", "world war three"],
    genres: ["k-pop", "grunge"],
  }),
  new Songs({
    id: v4(),
    title: "Track record",
    artists: ["644a88b5849a447b4d2c56da"],
    lyrics: "These people need to look at all the track records of all these people and stuff",
    about: "a political song",
    releaseDate: new Date(),
    producedBy: ["uniqlo"],
    writtenBy: ["twiztid tea"],
    composer: ["poster pal"],
    lyricist: ["the senator"],
    covers: ["member of state", "rage against the machine"],
    genres: ["rap", "grunge"],
  }),
  new Songs({
    id: v4(),
    title: "we are losing the war",
    artists: ["644a88b5849a447b4d2c56da"],
    lyrics: "We are losing the war for people's minds and you cannot hide this needle in a sack of hay",
    about: "another political song",
    releaseDate: new Date(),
    producedBy: ["diz-aggree"],
    writtenBy: ["seeds of chaos"],
    composer: ["sappling"],
    lyricist: ["the senator", "liz", "lez"],
    covers: ["system of governance", "started breaking"],
    genres: ["rap", "R+B"],
  }),
  new Songs({
    id: v4(),
    title: "Target the target",
    artists: ["644a88b5849a447b4d2c56da"],
    lyrics: "this is the most horrific and earth shaking news, I missed the target!",
    about: "children are under fire",
    releaseDate: new Date(),
    producedBy: ["aggro"],
    writtenBy: ["honorable Timmy", "liz"],
    composer: ["sappling", "big bubba"],
    lyricist: ["thrower"],
    covers: ["eugene", "hot diggity dog"],
    genres: ["rap"],
  }),
];

seeder(songs);
